### ISSUE TITLE
總頁數唔岩 sosad

### ISSUE THREAD

**Issue by Jasonlhy** [mingchuno/golden-cache#4]
好似會有奇怪既bug sosad

例如 [呢個高達post](http://plasticnofd.xyz/#/post/6136999/3)
個post 唔止4頁
但係佢只係顯示到4頁
係咪因為佢cache 左幾個record 有幾個 total pages

**Comment by mingchuno** [comment]
你岩, 因為cache左. known issue 來的, 會fix :)

**Comment by Jasonlhy** [comment]
巴打改左啲咩:o 依家又ok 返
